default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:170277646403:android:89f46a5188edca41d7a4f6",
        firebase_cli_token: "1//03al1jCFba_aCCgYIARAAGAMSNwF-L9IrwWI1hU0_yebphl6eHULJpAzKjqwpsKpWHQBdZ5zq8zP24nw56np45EujejZooQmYOqM",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "aladwymahmoud@gmail.com",
        release_notes: "student app done except 20%",
        upload_timeout: 600 
  )
  end
end




